config/routes.rb
Rails.application.routes.draw do
  resources :areas
  resources :companies do
    resources :employees, only: [:create, :destroy]
  end

  root 'companies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :employees
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :employees
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :company
  belongs_to :area
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:name)
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @employee = Employee.new
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  
  def create
    @employee = Employee.new(employee_params)
    
    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee.company, notice: 'El empleado ha sido creado.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to @employee.company, notice: 'El empleado fue eliminado' 
  end

  private
  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :email, :company_id, :area_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/areas/_form.html.erb
<%= form_with(model: area, local: true) do |form| %>
  <% if area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :area_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Areas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= area.name %></td>
        <td><%= link_to 'Show', area %></td>
        <td><%= link_to 'Edit', edit_area_path(area) %></td>
        <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Area', new_area_path %>

app/views/areas/new.html.erb
<h1>New Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Back', areas_path %>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @area.name %>
</p>

<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :company_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Company</h1>

<div class="row justify-content-center">
  <div class="col-xs-12 col-sm-12 col-md-12">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th>Nombre</th>
          <th>Empleados</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @companies.each do |company| %>
          <tr>
            <td><%= link_to company.name, company %></td>
            <td><%= company.employees.count %></td>
            <td>
              <%= link_to 'Edit', edit_company_path(company), class: 'btn btn-outline-info'%>
              <%= link_to 'Destroy', company, class: 'btn btn-outline-danger', 
              method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<div class="row justify-content-center">
  <div class="col-xs-12 col-sm-12 col-md-6">
    <h3> Compañia : <%= @company.name %></h3>

    <%= form_with(model: [@company, @employee]) do |form| %>
      <%= form.hidden_field :company_id, value: @company.id %>

      <div class="form-group">
        <%= form.label :first_name, 'Nombre' %>
        <%= form.text_field :first_name, id: :employee_first_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :last_name, 'Apellido' %>
        <%= form.text_field :last_name, id: :employee_last_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :email, 'Email' %>
        <%= form.email_field :email, id: :employee_email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :area_id, "Area" %>
        <%= form.select :area_id, Area.pluck(:name, :id), class: 'form-control' %>
      </div>

      <div class="actions">
        <%= form.submit 'Ingresar', class: 'btn btn-primary'%>
      </div>
    <% end %>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-xs-12 col-sm-12 col-md-12">
    <table class="table mt-3">
      <thead class="thead-dark">
        <tr>
          <th>Nombre</th>
          <th>Apellido</th>
          <th>Email</th>
          <th>Area</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @company.employees.each do |employee| %>
        <tr>
          <td><%= employee.first_name %></td>
          <td><%= employee.last_name %></td>
          <td><%= employee.email %></td>
          <td><%= employee.area.name %></td>
          <td>
            <%= link_to 'Eliminar', company_employee_path(@company, employee),
            class: 'btn btn-outline-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mx-auto">
      <li class="nav-item">
        <a class="btn btn-outline-info mx-1 my-1" href="<%= root_path %>">Home</a>
      </li>
      <li class="nav-item">
        <a class="btn btn-outline-success mx-1 my-1" href="<%= new_company_path %>">Nueva compañía</a>
      </li>
      <li class="nav-item">
        <a class="btn btn-outline-success mx-1 my-1" href="<%= new_area_path %>">Nueva área</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Actividad28</title>
    <%= csrf_meta_tags %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <% if alert.present? %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>

    <% if notice.present? %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>